// flow-typed signature: 1c5c5a37712bd945c8b504dbe6fff19b
// flow-typed version: <<STUB>>/bson-objectid_v^1.1.5/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bson-objectid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bson-objectid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bson-objectid/objectid' {
  declare module.exports: any;
}

declare module 'bson-objectid/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bson-objectid/objectid.js' {
  declare module.exports: $Exports<'bson-objectid/objectid'>;
}
declare module 'bson-objectid/test/test.js' {
  declare module.exports: $Exports<'bson-objectid/test/test'>;
}
